services:
  backend:
    build: .
    ports:
      - "5000"
    depends_on:
      - postgres
    restart: always
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: yarn build
    volumes:
      - ./frontend/build:/app/build
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - mynet

  postgres:
    image: postgres:15-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: always
    networks:
      - mynet

volumes:
  db-data: