services:
  backend:
    build: .
    ports:
      - "5000"
    depends_on:
      - postgres
    restart: always
    networks:
      - mynet
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - mynet
    depends_on:
      - backend
    deploy:
      replicas: 0 

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: always
    networks:
      - mynet

  postgres:
    image: postgres:15-alpine3.18
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: always
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet:
